### ISSUE TITLE
SyntaxError: missing ) after argument list

### ISSUE THREAD

**Issue by Enalmada** [krakenjs/xcomponent-demo#6]
When running `npm run webpack` on zoid-demo with Windows 10, I get the following error:
```
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^
SyntaxError: missing ) after argument list
```

Also happens using WSL.  It seems like the solution is to replace the string `./node_modules/.bin/webpack` in the package.json command with `./node_modules/webpack/bin/webpack.js`

```
"webpack": "babel-node --plugins=transform-es2015-modules-commonjs ./node_modules/webpack/bin/webpack.js --progress",
```
(credit: https://github.com/tylingsoft/markdown-plus/issues/89#issuecomment-339541606)

Hope this helps someone trying this out on Windows!

**Comment by mecanos28** [comment]
Thanks so much! Saved me at least 3 hours of my life.

**Comment by ghost** [comment]
thanks, I had the same issue when running an older project. This save me some hours as well.

**Comment by Jiso-Chacko** [comment]
Thanks a lot, saved a lot of time!

**Comment by jasvin-singh22** [comment]
Thanks a lot!!!!
